runtime: nodejs14
handlers:
  - url: /.*
    secure: always
    script: auto
env_variables:
  REACT_APP_FIREBASE_API_KEY: AIzaSyDgrD043PrYusBHt74PbAyFG_Eqjhb3mbA
  REACT_APP_FIREBASE_AUTH_DOMAIN: the-sc-website.firebaseapp.com
  REACT_APP_FIREBASE_PROJECT_ID: the-sc-website
  REACT_APP_FIREBASE_STORAGE_BUCKET: the-sc-website.appspot.com
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: 724396208046
  REACT_APP_FIREBASE_APP_ID: 1:724396208046:web:be8608d07838c724bf223f
  REACT_APP_FIREBASE_MEASUREMENT_ID: G-B67VE8K4D0
  MONGODB_URI: mongodb+srv://mainserver:1234@riscouncil.ah8x8.mongodb.net/riscouncil?retryWrites=true&w=majority